version: '3'

services:
  fastapi:
    build: .
    ports:
      - "8000:80"
    networks:
      - my_network_nginx

  nginx:
    image: nginx
    container_name: nginx
    networks:
      - my_network_nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      # - /etc/localtime:/etc/localtime:ro

networks:
  my_network_nginx:
    external: true
